// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ConversationType string

const (
	ConversationTypePrivate ConversationType = "private"
	ConversationTypeGroup   ConversationType = "group"
)

func (e *ConversationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConversationType(s)
	case string:
		*e = ConversationType(s)
	default:
		return fmt.Errorf("unsupported scan type for ConversationType: %T", src)
	}
	return nil
}

type NullConversationType struct {
	ConversationType ConversationType `json:"conversation_type"`
	Valid            bool             `json:"valid"` // Valid is true if ConversationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConversationType) Scan(value interface{}) error {
	if value == nil {
		ns.ConversationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConversationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConversationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConversationType), nil
}

type MemberRole string

const (
	MemberRoleAdmin  MemberRole = "admin"
	MemberRoleMember MemberRole = "member"
)

func (e *MemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRole(s)
	case string:
		*e = MemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRole: %T", src)
	}
	return nil
}

type NullMemberRole struct {
	MemberRole MemberRole `json:"member_role"`
	Valid      bool       `json:"valid"` // Valid is true if MemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRole), nil
}

type SystemEventType string

const (
	SystemEventTypeMemberJoined       SystemEventType = "member_joined"
	SystemEventTypeMemberLeft         SystemEventType = "member_left"
	SystemEventTypeMemberRemoved      SystemEventType = "member_removed"
	SystemEventTypeMemberAdded        SystemEventType = "member_added"
	SystemEventTypeChatCreated        SystemEventType = "chat_created"
	SystemEventTypeGroupCreated       SystemEventType = "group_created"
	SystemEventTypeGroupNameChanged   SystemEventType = "group_name_changed"
	SystemEventTypeGroupAvatarChanged SystemEventType = "group_avatar_changed"
	SystemEventTypeMemberPromoted     SystemEventType = "member_promoted"
	SystemEventTypeMemberDemoted      SystemEventType = "member_demoted"
)

func (e *SystemEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SystemEventType(s)
	case string:
		*e = SystemEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for SystemEventType: %T", src)
	}
	return nil
}

type NullSystemEventType struct {
	SystemEventType SystemEventType `json:"system_event_type"`
	Valid           bool            `json:"valid"` // Valid is true if SystemEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSystemEventType) Scan(value interface{}) error {
	if value == nil {
		ns.SystemEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SystemEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSystemEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SystemEventType), nil
}

type Conversation struct {
	ID        int64            `json:"id"`
	Type      ConversationType `json:"type"`
	CreatedAt time.Time        `json:"created_at"`
}

type ConversationMember struct {
	ConversationID int64      `json:"conversation_id"`
	UserID         int64      `json:"user_id"`
	Role           MemberRole `json:"role"`
	JoinedAt       time.Time  `json:"joined_at"`
}

type Group struct {
	ConversationID int64       `json:"conversation_id"`
	Name           string      `json:"name"`
	AvatarUrl      pgtype.Text `json:"avatar_url"`
	CreatedAt      time.Time   `json:"created_at"`
}

type Message struct {
	ID             int64     `json:"id"`
	Uuid           uuid.UUID `json:"uuid"`
	ConversationID int64     `json:"conversation_id"`
	SenderID       int64     `json:"sender_id"`
	Content        string    `json:"content"`
	SentAt         time.Time `json:"sent_at"`
}

type MessageRead struct {
	MessageID int64     `json:"message_id"`
	UserID    int64     `json:"user_id"`
	ReadAt    time.Time `json:"read_at"`
}

type SystemMessage struct {
	ID             int64           `json:"id"`
	Uuid           uuid.UUID       `json:"uuid"`
	ConversationID int64           `json:"conversation_id"`
	EventType      SystemEventType `json:"event_type"`
	ActorID        pgtype.Int8     `json:"actor_id"`
	TargetID       pgtype.Int8     `json:"target_id"`
	Content        pgtype.Text     `json:"content"`
	CreatedAt      time.Time       `json:"created_at"`
}
