// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	AddGroupMembers(ctx context.Context, arg AddGroupMembersParams) (AddGroupMembersRow, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error)
	CreateSystemMessage(ctx context.Context, arg CreateSystemMessageParams) (CreateSystemMessageRow, error)
	LeaveConversation(ctx context.Context, arg LeaveConversationParams) (LeaveConversationRow, error)
	// -- name: GetAllConversations :many
	// with user_conversations as (
	//     select conversation_id
	//     from conversation_members
	//     where user_id = $1
	// ),
	// all_timeline as (
	//     -- User messages
	//     select
	//         m.id,
	//         m.conversation_id,
	//         'user_message' as message_type,
	//         m.content as last_message,
	//         m.sent_at as last_message_time,
	//         m.sender_id,
	//         coalesce(p.name, u.display_name) as sender_name,
	//         null::bigint as actor_id,
	//         null::bigint as target_id,
	//         null::text as event_type,
	//         null::text as actor_name,
	//         null::text as target_name
	//     from messages m
	//     join users u on m.sender_id = u.user_id
	//     left join profiles p on m.sender_id = p.user_id
	//     union all
	//     -- System events with actor/target names
	//     select
	//         sm.id,
	//         sm.conversation_id,
	//         'system_event' as message_type,
	//         sm.content as last_message,
	//         sm.created_at as last_message_time,
	//         null::bigint as sender_id,
	//         null::text as sender_name,
	//         sm.actor_id,
	//         sm.target_id,
	//         sm.event_type::text as event_type,
	//         coalesce(actor_p.name, actor_u.display_name) as actor_name,
	//         coalesce(target_p.name, target_u.display_name) as target_name
	//     from system_messages sm
	//     left join users actor_u on sm.actor_id = actor_u.user_id
	//     left join users target_u on sm.target_id = target_u.user_id
	//     left join profiles actor_p on sm.actor_id = actor_p.user_id
	//     left join profiles target_p on sm.target_id = target_p.user_id
	// ),
	// latest_messages as (
	//     select distinct on (conversation_id)
	//         id,
	//         conversation_id,
	//         message_type,
	//         last_message,
	//         last_message_time,
	//         sender_id,
	//         sender_name,
	//         actor_id,
	//         target_id,
	//         event_type,
	//         actor_name,
	//         target_name
	//     from all_timeline
	//     order by conversation_id, last_message_time desc
	// )
	// select
	//     c.id as conversation_id,
	//     c.type as conversation_type,
	//     -- Name and avatar based on conversation type
	//     case
	//         when c.type = 'private' then
	//             (select p.name
	//              from conversation_members cm
	//              join profiles p on cm.user_id = p.user_id
	//              where cm.conversation_id = c.id
	//                and cm.user_id <> $1
	//              limit 1)
	//         else
	//             (select g.name
	//              from groups g
	//              where g.conversation_id = c.id)
	//     end as conversation_name,
	//     case
	//         when c.type = 'private' then
	//             (select p.avatar_url
	//              from conversation_members cm
	//              join profiles p on cm.user_id = p.user_id
	//              where cm.conversation_id = c.id
	//                and cm.user_id <> $1
	//              limit 1)
	//         else
	//             (select g.avatar_url
	//              from groups g
	//              where g.conversation_id = c.id)
	//     end as avatar_url,
	//     -- Last message info
	//     lm.message_type,
	//     lm.last_message,
	//     lm.last_message_time,
	//     lm.sender_id,
	//     lm.sender_name,
	//     lm.actor_id,
	//     lm.target_id,
	//     lm.event_type,
	//     lm.actor_name,
	//     lm.target_name,
	//     (mr.message_id is not null) as is_read
	// from user_conversations uc
	// join conversations c on uc.conversation_id = c.id
	// left join latest_messages lm on c.id = lm.conversation_id
	// left join message_reads mr on lm.id = mr.message_id and mr.user_id = $1
	// order by coalesce(lm.last_message_time, c.created_at) desc;
	// -- name: GetMessagesByConversationId :many
	// with combined_timeline as (
	//     select
	//         m.id,
	//         'user_message' as message_type,
	//         m.sender_id,
	//         null::bigint as actor_id,
	//         null::bigint as target_id,
	//         null::text as event_type,
	//         m.conversation_id,
	//         m.content,
	//         m.sent_at as created_at,
	//         coalesce(p.name, u.display_name) as sender_name,
	//         null::varchar(50) as target_name,
	//         p.avatar_url as sender_avatar,
	//         case
	//             when m.sender_id = $2 then 'sent'
	//             else 'received'
	//         end as message_direction
	//     from messages m
	//     join users u on u.user_id = m.sender_id
	//     left join profiles p on p.user_id = m.sender_id
	//     where m.conversation_id = $1
	//     union all
	//     select
	//         sm.id,
	//         'system_event' as message_type,
	//         null::bigint as sender_id,
	//         sm.actor_id,
	//         sm.target_id,
	//         sm.event_type::text as event_type,
	//         sm.conversation_id,
	//         sm.content,
	//         sm.created_at,
	//         coalesce(actor_p.name, actor_u.display_name) as sender_name,
	//         coalesce(target_p.name, target_u.display_name) as target_name,
	//         null::text as sender_avatar,
	//         null::text as message_direction
	//     from system_messages sm
	//     left join users actor_u on sm.actor_id = actor_u.user_id
	//     left join users target_u on sm.target_id = target_u.user_id
	//     left join profiles actor_p on sm.actor_id = actor_p.user_id
	//     left join profiles target_p on sm.target_id = target_p.user_id
	//     where sm.conversation_id = $1
	// )
	// select * from combined_timeline
	// where ($3::bigint is null or id < $3)
	// order by id desc
	// limit $4;
	MarkMessagesAsRead(ctx context.Context, arg MarkMessagesAsReadParams) error
	RemoveGroupMembers(ctx context.Context, arg RemoveGroupMembersParams) error
	// -- name: GetGroupMembers :many
	// select
	//     u.uuid,
	//     coalesce(p.name, u.display_name) as name,
	//     p.avatar_url,
	//     cm.role
	// from conversation_members cm
	// join users u on cm.user_id = u.user_id
	// left join profiles p on u.user_id = p.user_id
	// where cm.conversation_id = $1
	// order by coalesce(p.name, u.display_name);
	UpdateGroupInfo(ctx context.Context, arg UpdateGroupInfoParams) (Group, error)
}

var _ Querier = (*Queries)(nil)
