// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Profile struct {
	UserID        int64       `json:"user_id"`
	Name          string      `json:"name"`
	Email         pgtype.Text `json:"email"`
	Phone         pgtype.Text `json:"phone"`
	Birthday      pgtype.Date `json:"birthday"`
	AvatarUrl     pgtype.Text `json:"avatar_url"`
	AvatarVersion int32       `json:"avatar_version"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

type User struct {
	UserID      int64              `json:"user_id"`
	Uuid        uuid.UUID          `json:"uuid"`
	DisplayName string             `json:"display_name"`
	CreatedAt   time.Time          `json:"created_at"`
	IsActive    bool               `json:"is_active"`
	DisableAt   pgtype.Timestamptz `json:"disable_at"`
}
