// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	// -- name: GetUserByUUID :one
	// -- Get user info with friendship/friend request status
	// -- $1: target_user_uuid (user being searched)
	// -- $2: current_user_id (user doing the search)
	// SELECT
	//     u.user_id,
	//     u.uuid,
	//     p.name,
	//     p.avatar_url,
	//     -- Friend request status (if exists)
	//     CASE
	//         WHEN fr.status = 'pending' AND fr.sender_id = $2 THEN 'sent'
	//         WHEN fr.status = 'pending' AND fr.receiver_id = $2 THEN 'received'
	//         ELSE fr.status
	//     END as friend_request_direction,
	//     -- Friendship status (if exists)
	//     CASE
	//         WHEN f.user1_id IS NOT NULL THEN true
	//         ELSE false
	//     END as is_friend
	// FROM users u
	// -- Check if there's a pending/accepted friend request
	// LEFT JOIN friend_requests fr
	//     ON (fr.sender_id = $2 AND fr.receiver_id = u.user_id)
	//     OR (fr.sender_id = u.user_id AND fr.receiver_id = $2)
	// -- Check if already friends
	// LEFT JOIN friendships f
	//     ON (f.user1_id = LEAST($2, u.user_id) AND f.user2_id = GREATEST($2, u.user_id))
	// LEFT JOIN profiles p
	//     ON p.user_id = u.user_id
	// WHERE u.uuid = $1 and u.is_active = true and u.user_id <> $2;
	ActiveUser(ctx context.Context, userID int64) (pgconn.CommandTag, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	CreateUser(ctx context.Context, displayName string) (int64, error)
	DeleteUser(ctx context.Context, userID int64) (pgconn.CommandTag, error)
	DisableUser(ctx context.Context, userID int64) error
	GetProfileByUserId(ctx context.Context, userID int64) (GetProfileByUserIdRow, error)
	GetProfileByUserUUID(ctx context.Context, arg GetProfileByUserUUIDParams) (GetProfileByUserUUIDRow, error)
	GetUUIDByUserId(ctx context.Context, userID int64) (uuid.UUID, error)
	IsExistProfile(ctx context.Context, userID int64) (bool, error)
	UpdateProfileAvatarByUserId(ctx context.Context, arg UpdateProfileAvatarByUserIdParams) (UpdateProfileAvatarByUserIdRow, error)
	UpdateProfileByUserId(ctx context.Context, arg UpdateProfileByUserIdParams) (UpdateProfileByUserIdRow, error)
}

var _ Querier = (*Queries)(nil)
