// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const activeUser = `-- name: ActiveUser :execresult
    
    
    





UPDATE users SET is_active = true, disable_at = null 
WHERE user_id = $1
AND is_active = false
AND disable_at > now() - interval '30 days'
`

// -- name: GetUserByUUID :one
// -- Get user info with friendship/friend request status
// -- $1: target_user_uuid (user being searched)
// -- $2: current_user_id (user doing the search)
// SELECT
//
//	u.user_id,
//	u.uuid,
//	p.name,
//	p.avatar_url,
//	-- Friend request status (if exists)
//	CASE
//	    WHEN fr.status = 'pending' AND fr.sender_id = $2 THEN 'sent'
//	    WHEN fr.status = 'pending' AND fr.receiver_id = $2 THEN 'received'
//	    ELSE fr.status
//	END as friend_request_direction,
//	-- Friendship status (if exists)
//	CASE
//	    WHEN f.user1_id IS NOT NULL THEN true
//	    ELSE false
//	END as is_friend
//
// FROM users u
// -- Check if there's a pending/accepted friend request
// LEFT JOIN friend_requests fr
//
//	ON (fr.sender_id = $2 AND fr.receiver_id = u.user_id)
//	OR (fr.sender_id = u.user_id AND fr.receiver_id = $2)
//
// -- Check if already friends
// LEFT JOIN friendships f
//
//	ON (f.user1_id = LEAST($2, u.user_id) AND f.user2_id = GREATEST($2, u.user_id))
//
// LEFT JOIN profiles p
//
//	ON p.user_id = u.user_id
//
// WHERE u.uuid = $1 and u.is_active = true and u.user_id <> $2;
func (q *Queries) ActiveUser(ctx context.Context, userID int64) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, activeUser, userID)
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (display_name) VALUES ($1) RETURNING user_id
`

func (q *Queries) CreateUser(ctx context.Context, displayName string) (int64, error) {
	row := q.db.QueryRow(ctx, createUser, displayName)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const deleteUser = `-- name: DeleteUser :execresult
DELETE FROM users WHERE user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userID int64) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteUser, userID)
}

const disableUser = `-- name: DisableUser :exec
UPDATE users SET is_active = false, disable_at = now() WHERE user_id = $1
`

func (q *Queries) DisableUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, disableUser, userID)
	return err
}

const getUUIDByUserId = `-- name: GetUUIDByUserId :one
SELECT uuid FROM users WHERE user_id = $1
`

func (q *Queries) GetUUIDByUserId(ctx context.Context, userID int64) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUUIDByUserId, userID)
	var uuid uuid.UUID
	err := row.Scan(&uuid)
	return uuid, err
}

const isExistProfile = `-- name: IsExistProfile :one
SELECT EXISTS (SELECT 1 FROM profiles WHERE user_id = $1)
`

func (q *Queries) IsExistProfile(ctx context.Context, userID int64) (bool, error) {
	row := q.db.QueryRow(ctx, isExistProfile, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
