// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const activeUser = `-- name: ActiveUser :execresult
UPDATE users SET is_active = true, disable_at = null 
WHERE user_id = $1
AND is_active = false
AND disable_at > now() - interval '30 days'
`

func (q *Queries) ActiveUser(ctx context.Context, userID int64) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, activeUser, userID)
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (display_name) VALUES ($1) RETURNING user_id
`

func (q *Queries) CreateUser(ctx context.Context, displayName string) (int64, error) {
	row := q.db.QueryRow(ctx, createUser, displayName)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const deleteUser = `-- name: DeleteUser :execresult
DELETE FROM users WHERE user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userID int64) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteUser, userID)
}

const disableUser = `-- name: DisableUser :exec
UPDATE users SET is_active = false, disable_at = now() WHERE user_id = $1
`

func (q *Queries) DisableUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, disableUser, userID)
	return err
}

const getUUIDByUserId = `-- name: GetUUIDByUserId :one
SELECT uuid FROM users WHERE user_id = $1
`

func (q *Queries) GetUUIDByUserId(ctx context.Context, userID int64) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUUIDByUserId, userID)
	var uuid uuid.UUID
	err := row.Scan(&uuid)
	return uuid, err
}

const getUserByUUID = `-- name: GetUserByUUID :one
SELECT 
    u.user_id,
    p.name,
    u.is_active,
    p.avatar_url,
    p.avatar_version
    
FROM users u

LEFT JOIN profiles p
    ON p.user_id = u.user_id

WHERE u.uuid = $1 and u.user_id <> $2
`

type GetUserByUUIDParams struct {
	TargetUserUuid uuid.UUID `json:"target_user_uuid"`
	CurrentUserID  int64     `json:"current_user_id"`
}

type GetUserByUUIDRow struct {
	UserID        int64       `json:"user_id"`
	Name          pgtype.Text `json:"name"`
	IsActive      bool        `json:"is_active"`
	AvatarUrl     pgtype.Text `json:"avatar_url"`
	AvatarVersion pgtype.Int4 `json:"avatar_version"`
}

func (q *Queries) GetUserByUUID(ctx context.Context, arg GetUserByUUIDParams) (GetUserByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByUUID, arg.TargetUserUuid, arg.CurrentUserID)
	var i GetUserByUUIDRow
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.IsActive,
		&i.AvatarUrl,
		&i.AvatarVersion,
	)
	return i, err
}

const isExistProfile = `-- name: IsExistProfile :one
SELECT EXISTS (SELECT 1 FROM profiles WHERE user_id = $1)
`

func (q *Queries) IsExistProfile(ctx context.Context, userID int64) (bool, error) {
	row := q.db.QueryRow(ctx, isExistProfile, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
