// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/grpc/auth/auth.proto

package auth_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorCode    string                 `protobuf:"bytes,1,opt,name=author_code,json=authorCode,proto3" json:"author_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_internal_grpc_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetAuthorCode() string {
	if x != nil {
		return x.AuthorCode
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_internal_grpc_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *LoginResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

var File_internal_grpc_auth_auth_proto protoreflect.FileDescriptor

const file_internal_grpc_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/grpc/auth/auth.proto\x12\x05proto\"/\n" +
	"\fLoginRequest\x12\x1f\n" +
	"\vauthor_code\x18\x01 \x01(\tR\n" +
	"authorCode\"_\n" +
	"\rLoginResponse\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId2G\n" +
	"\vAuthService\x128\n" +
	"\vLoginGoogle\x12\x13.proto.LoginRequest\x1a\x14.proto.LoginResponseB\x1fZ\x1dinternal/grpc/auth;auth_protob\x06proto3"

var (
	file_internal_grpc_auth_auth_proto_rawDescOnce sync.Once
	file_internal_grpc_auth_auth_proto_rawDescData []byte
)

func file_internal_grpc_auth_auth_proto_rawDescGZIP() []byte {
	file_internal_grpc_auth_auth_proto_rawDescOnce.Do(func() {
		file_internal_grpc_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_auth_auth_proto_rawDesc), len(file_internal_grpc_auth_auth_proto_rawDesc)))
	})
	return file_internal_grpc_auth_auth_proto_rawDescData
}

var file_internal_grpc_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_grpc_auth_auth_proto_goTypes = []any{
	(*LoginRequest)(nil),  // 0: proto.LoginRequest
	(*LoginResponse)(nil), // 1: proto.LoginResponse
}
var file_internal_grpc_auth_auth_proto_depIdxs = []int32{
	0, // 0: proto.AuthService.LoginGoogle:input_type -> proto.LoginRequest
	1, // 1: proto.AuthService.LoginGoogle:output_type -> proto.LoginResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpc_auth_auth_proto_init() }
func file_internal_grpc_auth_auth_proto_init() {
	if File_internal_grpc_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_auth_auth_proto_rawDesc), len(file_internal_grpc_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_auth_auth_proto_goTypes,
		DependencyIndexes: file_internal_grpc_auth_auth_proto_depIdxs,
		MessageInfos:      file_internal_grpc_auth_auth_proto_msgTypes,
	}.Build()
	File_internal_grpc_auth_auth_proto = out.File
	file_internal_grpc_auth_auth_proto_goTypes = nil
	file_internal_grpc_auth_auth_proto_depIdxs = nil
}
