// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/grpc/auth/auth.proto

package auth_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAPIKeyRequest) Reset() {
	*x = ValidateAPIKeyRequest{}
	mi := &file_internal_grpc_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAPIKeyRequest) ProtoMessage() {}

func (x *ValidateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*ValidateAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateAPIKeyRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type ValidateAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAPIKeyResponse) Reset() {
	*x = ValidateAPIKeyResponse{}
	mi := &file_internal_grpc_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAPIKeyResponse) ProtoMessage() {}

func (x *ValidateAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*ValidateAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateAPIKeyResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateAPIKeyResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_internal_grpc_auth_auth_proto protoreflect.FileDescriptor

const file_internal_grpc_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/grpc/auth/auth.proto\x12\x05proto\"0\n" +
	"\x15ValidateAPIKeyRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"@\n" +
	"\x16ValidateAPIKeyResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg2\\\n" +
	"\vAuthService\x12M\n" +
	"\x0eValidateAPIKey\x12\x1c.proto.ValidateAPIKeyRequest\x1a\x1d.proto.ValidateAPIKeyResponseB\x1fZ\x1dinternal/grpc/auth;auth_protob\x06proto3"

var (
	file_internal_grpc_auth_auth_proto_rawDescOnce sync.Once
	file_internal_grpc_auth_auth_proto_rawDescData []byte
)

func file_internal_grpc_auth_auth_proto_rawDescGZIP() []byte {
	file_internal_grpc_auth_auth_proto_rawDescOnce.Do(func() {
		file_internal_grpc_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_auth_auth_proto_rawDesc), len(file_internal_grpc_auth_auth_proto_rawDesc)))
	})
	return file_internal_grpc_auth_auth_proto_rawDescData
}

var file_internal_grpc_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_grpc_auth_auth_proto_goTypes = []any{
	(*ValidateAPIKeyRequest)(nil),  // 0: proto.ValidateAPIKeyRequest
	(*ValidateAPIKeyResponse)(nil), // 1: proto.ValidateAPIKeyResponse
}
var file_internal_grpc_auth_auth_proto_depIdxs = []int32{
	0, // 0: proto.AuthService.ValidateAPIKey:input_type -> proto.ValidateAPIKeyRequest
	1, // 1: proto.AuthService.ValidateAPIKey:output_type -> proto.ValidateAPIKeyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpc_auth_auth_proto_init() }
func file_internal_grpc_auth_auth_proto_init() {
	if File_internal_grpc_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_auth_auth_proto_rawDesc), len(file_internal_grpc_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_auth_auth_proto_goTypes,
		DependencyIndexes: file_internal_grpc_auth_auth_proto_depIdxs,
		MessageInfos:      file_internal_grpc_auth_auth_proto_msgTypes,
	}.Build()
	File_internal_grpc_auth_auth_proto = out.File
	file_internal_grpc_auth_auth_proto_goTypes = nil
	file_internal_grpc_auth_auth_proto_depIdxs = nil
}
