steps:
  # ================= API GATEWAY =================
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker pull us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/api-gateway:latest || exit 0

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--cache-from",
        "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/api-gateway:latest",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/api-gateway:$SHORT_SHA",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/api-gateway:latest",
        "-f",
        "backend/Dockerfile.api",
        "backend",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/api-gateway:$SHORT_SHA",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/api-gateway:latest",
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      [
        "gcloud",
        "run",
        "deploy",
        "chat-app-api-gateway",
        "--image",
        "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/api-gateway:$SHORT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--command",
        "./main",
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e
        gcloud container clusters get-credentials chat-app-cluster --region us-central1 --project $PROJECT_ID
        kubectl set image deployment/api-gateway-deployment api-gateway-sha256-1=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/api-gateway:$SHORT_SHA
        kubectl rollout status deployment/api-gateway-deployment

  # ================= AUTH SERVICE =================
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker pull us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/auth-service:latest || exit 0

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--cache-from",
        "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/auth-service:latest",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/auth-service:$SHORT_SHA",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/auth-service:latest",
        "-f",
        "backend/Dockerfile.auth",
        "backend",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/auth-service:$SHORT_SHA",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/auth-service:latest",
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      [
        "gcloud",
        "run",
        "deploy",
        "chat-app-auth-service",
        "--image",
        "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/auth-service:$SHORT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--command",
        "./main",
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e
        gcloud container clusters get-credentials chat-app-cluster --region us-central1 --project $PROJECT_ID
        kubectl set image deployment/auth-service-deployment auth-service-sha256-1=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/auth-service:$SHORT_SHA
        kubectl rollout status deployment/auth-service-deployment

  # ================= USER SERVICE =================
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker pull us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/user-service:latest || exit 0

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--cache-from",
        "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/user-service:latest",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/user-service:$SHORT_SHA",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/user-service:latest",
        "-f",
        "backend/Dockerfile.user",
        "backend",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/user-service:$SHORT_SHA",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/user-service:latest",
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      [
        "gcloud",
        "run",
        "deploy",
        "chat-app-user-service",
        "--image",
        "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/user-service:$SHORT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--command",
        "./main",
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e
        gcloud container clusters get-credentials chat-app-cluster --region us-central1 --project $PROJECT_ID
        kubectl set image deployment/user-service-deployment user-service-sha256-1=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/user-service:$SHORT_SHA
        kubectl rollout status deployment/user-service-deployment

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/api-gateway:$SHORT_SHA"
  - "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/auth-service:$SHORT_SHA"
  - "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/user-service:$SHORT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
