// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friend.sql

package sqlc

import (
	"context"
)

const addFriendById = `-- name: AddFriendById :one
select f.status::boolean, f.message::text from send_friend_request($1, $2) as f
`

type AddFriendByIdParams struct {
	PSenderID   int64 `json:"p_sender_id"`
	PReceiverID int64 `json:"p_receiver_id"`
}

type AddFriendByIdRow struct {
	FStatus  bool   `json:"f_status"`
	FMessage string `json:"f_message"`
}

func (q *Queries) AddFriendById(ctx context.Context, arg AddFriendByIdParams) (AddFriendByIdRow, error) {
	row := q.db.QueryRow(ctx, addFriendById, arg.PSenderID, arg.PReceiverID)
	var i AddFriendByIdRow
	err := row.Scan(&i.FStatus, &i.FMessage)
	return i, err
}

const getInfoRelationship = `-- name: GetInfoRelationship :one
select     
    -- Friend request status (if exists)
    case
        when f.user1_id is not null then null
        when fr.is_accepted = false and fr.sender_id = $1 then 'sent'
        when fr.is_accepted = false and fr.receiver_id = $1 then 'received'
        else null
    end::text as friend_request_direction,
    
    -- Friendship status (if exists)
    (f.user1_id is not null)::boolean as is_friend

from (select 1) as dummy

left join friend_requests fr 
    on (fr.sender_id = $1 and fr.receiver_id = $2)
    or (fr.sender_id = $2 and fr.receiver_id = $1)

left join friendships f
    on (f.user1_id = LEAST($1, $2) and f.user2_id = GREATEST($1, $2))

where $2 <> $1
`

type GetInfoRelationshipParams struct {
	CurrentUserID int64 `json:"current_user_id"`
	TargetUserID  int64 `json:"target_user_id"`
}

type GetInfoRelationshipRow struct {
	FriendRequestDirection string `json:"friend_request_direction"`
	IsFriend               bool   `json:"is_friend"`
}

// Get user info with friendship/friend request status
// Check if there's a pending/accepted friend request
// Check if already friends
func (q *Queries) GetInfoRelationship(ctx context.Context, arg GetInfoRelationshipParams) (GetInfoRelationshipRow, error) {
	row := q.db.QueryRow(ctx, getInfoRelationship, arg.CurrentUserID, arg.TargetUserID)
	var i GetInfoRelationshipRow
	err := row.Scan(&i.FriendRequestDirection, &i.IsFriend)
	return i, err
}

const rejectFriendRequestById = `-- name: RejectFriendRequestById :exec






delete from friend_requests
where request_id = $1 and receiver_id = $2 and status = 'pending'
`

type RejectFriendRequestByIdParams struct {
	RequestID  int64 `json:"request_id"`
	ReceiverID int64 `json:"receiver_id"`
}

// -- name: GetPendingFriendRequests :many
// select fr.request_id, u.uuid, p.name, p.avatar_url, fr.send_at
// from friend_requests fr
// join users u on fr.sender_id = u.user_id
// left join profiles p on fr.sender_id = p.user_id
// where fr.receiver_id = $1 and fr.status = 'pending'
// order by fr.send_at desc;
// -- name: GetSentFriendRequests :many
// select fr.request_id, u.uuid, p.name, p.avatar_url, fr.send_at
// from friend_requests fr
// join users u on fr.receiver_id = u.user_id
// left join profiles p on fr.receiver_id = p.user_id
// where fr.sender_id = $1 and fr.status = 'pending'
// order by fr.send_at desc;
// -- name: GetFriendsList :many
// with friend_ids as (
//
//	select f.user1_id as id from friendships f where f.user2_id = $1
//	union all
//	select f.user2_id as id from friendships f where f.user1_id = $1
//
// )
// select
//
//	u.uuid,
//	u.user_id,
//	coalesce(p.name, u.display_name) as name,
//	p.avatar_url,
//	u.is_active
//
// from users u
// left join profiles p on u.user_id = p.user_id
// join friend_ids f on u.user_id = f.id
// order by coalesce(p.name, u.display_name);
// -- name: SearchFriendByName :many
// with friend_ids as (
//
//	select f.user1_id as id from friendships f where f.user2_id = $1
//	union all
//	select f.user2_id as id from friendships f where f.user1_id = $1
//
// )
// select
//
//	u.uuid,
//	u.user_id,
//	coalesce(p.name, u.display_name) as name,
//	p.avatar_url,
//	u.is_active
//
// from users u
// left join profiles p on u.user_id = p.user_id
// join friend_ids f on u.user_id = f.id
// where coalesce(p.name, u.display_name) ilike '%' || $2 || '%'
// order by coalesce(p.name, u.display_name);
func (q *Queries) RejectFriendRequestById(ctx context.Context, arg RejectFriendRequestByIdParams) error {
	_, err := q.db.Exec(ctx, rejectFriendRequestById, arg.RequestID, arg.ReceiverID)
	return err
}
