// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type FriendRequest struct {
	RequestID  int64     `json:"request_id"`
	SenderID   int64     `json:"sender_id"`
	ReceiverID int64     `json:"receiver_id"`
	IsAccepted bool      `json:"is_accepted"`
	SendAt     time.Time `json:"send_at"`
}

type Friendship struct {
	User1ID       int64     `json:"user1_id"`
	User2ID       int64     `json:"user2_id"`
	EstablishedAt time.Time `json:"established_at"`
}
