// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkSession = `-- name: CheckSession :one
select user_id, revoked, revoke_at
from sessions 
where session_id = $1
`

type CheckSessionRow struct {
	UserID   int64              `json:"user_id"`
	Revoked  bool               `json:"revoked"`
	RevokeAt pgtype.Timestamptz `json:"revoke_at"`
}

func (q *Queries) CheckSession(ctx context.Context, sessionID uuid.UUID) (CheckSessionRow, error) {
	row := q.db.QueryRow(ctx, checkSession, sessionID)
	var i CheckSessionRow
	err := row.Scan(&i.UserID, &i.Revoked, &i.RevokeAt)
	return i, err
}

const cleanupSessionTable = `-- name: CleanupSessionTable :exec
delete from sessions where revoked = true and revoke_at < now() - interval '1 days'
`

func (q *Queries) CleanupSessionTable(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupSessionTable)
	return err
}

const createAPIKey = `-- name: CreateAPIKey :exec
insert into api_keys (key_hash) values ($1)
`

// manage apikeys
func (q *Queries) CreateAPIKey(ctx context.Context, keyHash string) error {
	_, err := q.db.Exec(ctx, createAPIKey, keyHash)
	return err
}

const createIdentity = `-- name: CreateIdentity :exec
insert into auth_identities (user_id, provider, provider_user_id, email)
values ($1, $2, $3, $4)
`

type CreateIdentityParams struct {
	UserID         int64       `json:"user_id"`
	Provider       string      `json:"provider"`
	ProviderUserID string      `json:"provider_user_id"`
	Email          pgtype.Text `json:"email"`
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) error {
	_, err := q.db.Exec(ctx, createIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Email,
	)
	return err
}

const createSession = `-- name: CreateSession :one
insert into sessions (user_id) values ($1) returning session_id
`

func (q *Queries) CreateSession(ctx context.Context, userID int64) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createSession, userID)
	var session_id uuid.UUID
	err := row.Scan(&session_id)
	return session_id, err
}

const findExistingIdentity = `-- name: FindExistingIdentity :one
select user_id from auth_identities 
where provider = $1 and provider_user_id = $2
`

type FindExistingIdentityParams struct {
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

func (q *Queries) FindExistingIdentity(ctx context.Context, arg FindExistingIdentityParams) (int64, error) {
	row := q.db.QueryRow(ctx, findExistingIdentity, arg.Provider, arg.ProviderUserID)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const revokeAPIKeyByKey = `-- name: RevokeAPIKeyByKey :exec
update api_keys set is_active = false, revoked_at = now() where key_hash = $1
`

func (q *Queries) RevokeAPIKeyByKey(ctx context.Context, keyHash string) error {
	_, err := q.db.Exec(ctx, revokeAPIKeyByKey, keyHash)
	return err
}

const revokeAllAPIKeys = `-- name: RevokeAllAPIKeys :exec
update api_keys set is_active = false, revoked_at = now() where is_active = true
`

func (q *Queries) RevokeAllAPIKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, revokeAllAPIKeys)
	return err
}

const revokeAllSessions = `-- name: RevokeAllSessions :exec
update sessions set revoked = true, revoke_at = now() where user_id = $1
`

func (q *Queries) RevokeAllSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeAllSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
update sessions set revoked = true, revoke_at = now() where session_id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, sessionID)
	return err
}

const validateAPIKey = `-- name: ValidateAPIKey :one
select is_active from api_keys where key_hash = $1
`

func (q *Queries) ValidateAPIKey(ctx context.Context, keyHash string) (bool, error) {
	row := q.db.QueryRow(ctx, validateAPIKey, keyHash)
	var is_active bool
	err := row.Scan(&is_active)
	return is_active, err
}
