// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const cleanupSessionTable = `-- name: CleanupSessionTable :exec
delete from sessions where revoked = true and revoke_at < now() - interval '1 days'
`

func (q *Queries) CleanupSessionTable(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupSessionTable)
	return err
}

const createAPIKey = `-- name: CreateAPIKey :exec
insert into api_keys (key_hash) values ($1)
`

// manage apikeys
func (q *Queries) CreateAPIKey(ctx context.Context, keyHash string) error {
	_, err := q.db.Exec(ctx, createAPIKey, keyHash)
	return err
}

const revokeAPIKeyByKey = `-- name: RevokeAPIKeyByKey :exec
update api_keys set is_active = false, revoked_at = now() where key_hash = $1
`

func (q *Queries) RevokeAPIKeyByKey(ctx context.Context, keyHash string) error {
	_, err := q.db.Exec(ctx, revokeAPIKeyByKey, keyHash)
	return err
}

const revokeAllAPIKeys = `-- name: RevokeAllAPIKeys :exec
update api_keys set is_active = false, revoked_at = now() where is_active = true
`

func (q *Queries) RevokeAllAPIKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, revokeAllAPIKeys)
	return err
}

const revokeAllSessions = `-- name: RevokeAllSessions :exec
update sessions set revoked = true, revoke_at = now() where user_id = $1
`

func (q *Queries) RevokeAllSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeAllSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec

update sessions set revoked = true, revoke_at = now() where session_id = $1
`

// -- name: CheckSession :one
// select s.user_id, u.uuid, s.revoked, s.revoke_at
// from sessions as s
// join users as u on s.user_id = u.id
// where session_id = $1 and device_id = $2 and u.is_active = true;
func (q *Queries) RevokeSession(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, sessionID)
	return err
}

const validateAPIKey = `-- name: ValidateAPIKey :one
select is_active from api_keys where key_hash = $1
`

func (q *Queries) ValidateAPIKey(ctx context.Context, keyHash string) (bool, error) {
	row := q.db.QueryRow(ctx, validateAPIKey, keyHash)
	var is_active bool
	err := row.Scan(&is_active)
	return is_active, err
}
