// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID        int64              `json:"id"`
	KeyHash   string             `json:"key_hash"`
	IsActive  bool               `json:"is_active"`
	CreatedAt time.Time          `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type AuthIdentity struct {
	ID             int64       `json:"id"`
	UserID         int64       `json:"user_id"`
	Provider       string      `json:"provider"`
	ProviderUserID string      `json:"provider_user_id"`
	Email          pgtype.Text `json:"email"`
	CreatedAt      time.Time   `json:"created_at"`
}

type Session struct {
	SessionID uuid.UUID          `json:"session_id"`
	UserID    int64              `json:"user_id"`
	Revoked   bool               `json:"revoked"`
	RevokeAt  pgtype.Timestamptz `json:"revoke_at"`
	CreatedAt time.Time          `json:"created_at"`
}
