// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CheckSession(ctx context.Context, sessionID uuid.UUID) (CheckSessionRow, error)
	CleanupSessionTable(ctx context.Context) error
	// manage apikeys
	CreateAPIKey(ctx context.Context, keyHash string) error
	CreateIdentity(ctx context.Context, arg CreateIdentityParams) error
	CreateSession(ctx context.Context, userID int64) (uuid.UUID, error)
	FindExistingIdentity(ctx context.Context, arg FindExistingIdentityParams) (int64, error)
	RevokeAPIKeyByKey(ctx context.Context, keyHash string) error
	RevokeAllAPIKeys(ctx context.Context) error
	RevokeAllSessions(ctx context.Context, userID int64) error
	RevokeSession(ctx context.Context, sessionID uuid.UUID) error
	ValidateAPIKey(ctx context.Context, keyHash string) (bool, error)
}

var _ Querier = (*Queries)(nil)
