// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CleanupSessionTable(ctx context.Context) error
	// manage apikeys
	CreateAPIKey(ctx context.Context, keyHash string) error
	RevokeAPIKeyByKey(ctx context.Context, keyHash string) error
	RevokeAllAPIKeys(ctx context.Context) error
	RevokeAllSessions(ctx context.Context, userID int64) error
	// -- name: CheckSession :one
	// select s.user_id, u.uuid, s.revoked, s.revoke_at
	// from sessions as s
	// join users as u on s.user_id = u.id
	// where session_id = $1 and device_id = $2 and u.is_active = true;
	RevokeSession(ctx context.Context, sessionID uuid.UUID) error
	ValidateAPIKey(ctx context.Context, keyHash string) (bool, error)
}

var _ Querier = (*Queries)(nil)
